name: Lint-pydocstyle

on: [push, pull_request]

jobs:
  pydocstyle:
    # NOTE: Uncomment the following line to disable
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-lint
    - name: Run pydocstyle
      run: |
        make pydocstyle-check
